Algoritmo "LogiFast_desafio3"
// 
//  
// Descrição   : Um programa que administra pedidos de uma empresa, organiza
//               entregas, defini prioridades, acompanha cargas e auxilia na
//               tomada de decisoes.
// Autor(a)    : Lucas Reghin Santos
// Data atual  : 9/30/2026
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo
